// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: application.proto

package serialization.protobuf;

public final class CrawlerProto {
  private CrawlerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Website_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Website_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Websites_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Websites_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021application.proto\"5\n\007Website\022\014\n\004name\030\001" +
      " \001(\t\022\017\n\007content\030\002 \001(\t\022\013\n\003url\030\003 \001(\t\"%\n\010We" +
      "bsites\022\031\n\007website\030\001 \003(\0132\010.WebsiteB(\n\026ser" +
      "ialization.protobufB\014CrawlerProtoP\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Website_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Website_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Website_descriptor,
        new java.lang.String[] { "Name", "Content", "Url", });
    internal_static_Websites_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Websites_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Websites_descriptor,
        new java.lang.String[] { "Website", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
