// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: application.proto

package serialization.protobuf;

public interface WebsitesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Websites)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Website website = 1;</code>
   */
  java.util.List<serialization.protobuf.Website> 
      getWebsiteList();
  /**
   * <code>repeated .Website website = 1;</code>
   */
  serialization.protobuf.Website getWebsite(int index);
  /**
   * <code>repeated .Website website = 1;</code>
   */
  int getWebsiteCount();
  /**
   * <code>repeated .Website website = 1;</code>
   */
  java.util.List<? extends serialization.protobuf.WebsiteOrBuilder> 
      getWebsiteOrBuilderList();
  /**
   * <code>repeated .Website website = 1;</code>
   */
  serialization.protobuf.WebsiteOrBuilder getWebsiteOrBuilder(
      int index);
}
